grep -q "MOVE_PETAL_DANCE" include/constants/moves.h || echo "Missing MOVE_PETAL_DANCE"
grep -q "MOVE_SEED_BOMB" include/constants/moves.h || echo "Missing MOVE_SEED_BOMB"
grep -q "MOVE_WORRY_SEED" include/constants/moves.h || echo "Missing MOVE_WORRY_SEED"
grep -q "MOVE_POWER_WHIP" include/constants/moves.h || echo "Missing MOVE_POWER_WHIP"
grep -q "MOVE_DRAGON_BREATH" include/constants/moves.h || echo "Missing MOVE_DRAGON_BREATH"
grep -q "MOVE_FIRE_FANG" include/constants/moves.h || echo "Missing MOVE_FIRE_FANG"
grep -q "MOVE_INFERNO" include/constants/moves.h || echo "Missing MOVE_INFERNO"
grep -q "MOVE_FLARE_BLITZ" include/constants/moves.h || echo "Missing MOVE_FLARE_BLITZ"
grep -q "MOVE_AIR_SLASH" include/constants/moves.h || echo "Missing MOVE_AIR_SLASH"
grep -q "MOVE_DRAGON_CLAW" include/constants/moves.h || echo "Missing MOVE_DRAGON_CLAW"
grep -q "MOVE_WATER_PULSE" include/constants/moves.h || echo "Missing MOVE_WATER_PULSE"
grep -q "MOVE_AQUA_TAIL" include/constants/moves.h || echo "Missing MOVE_AQUA_TAIL"
grep -q "MOVE_SHELL_SMASH" include/constants/moves.h || echo "Missing MOVE_SHELL_SMASH"
grep -q "MOVE_IRON_DEFENSE" include/constants/moves.h || echo "Missing MOVE_IRON_DEFENSE"
grep -q "MOVE_WAVE_CRASH" include/constants/moves.h || echo "Missing MOVE_WAVE_CRASH"
grep -q "MOVE_FLASH_CANNON" include/constants/moves.h || echo "Missing MOVE_FLASH_CANNON"
echo "Done"
